### ISSUE TITLE
Allow versions of stdlib below 6.0.0

### ISSUE THREAD

**Issue by saz** [rtib/puppet-geoip#34]
I don't see any reason, why puppetlabs/stdlib needs to be version 6.0.0 or higher.
The only thing used from stdlib is the type `Absolutepath` and this exists since more than 5 years.

If I'm not missing anything, I'll send a pull request to lower the required stdlib version to 4.13.0 (introduced AbsolutePath).

This will make the module compatible to other modules (e.g. I'm currently stuck at stdlib 5.2.0)

**Comment by saz** [comment]
While looking at dependencies, I don't see any usage of the puppetlabs/concat module?

**Comment by rtib** [comment]
We can lower the version requirement of puppetlabs/stdlib to 4.13.1, as low as the transient requirement from camptocamp/systemd.
